# permissions for end users to view podevents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: podevent-viewer-role
rules:
- apiGroups:
  - hound.io
  resources:
  - podevents
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hound.io
  resources:
  - podevents/status
  verbs:
  - get
