# permissions for end users to edit podevents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: podevent-editor-role
rules:
- apiGroups:
  - hound.io
  resources:
  - podevents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hound.io
  resources:
  - podevents/status
  verbs:
  - get
